FROM jekyll/jekyll

# these need to match the list in site-defaults.yml
RUN gem install jekyll-coffeescript \
  jekyll-commonmark-ghpages \
  jekyll-gist \
  jekyll-github-metadata \
  jekyll-paginate \
  jekyll-relative-links \
  jekyll-optional-front-matter \
  jekyll-readme-index \
  jekyll-default-layout \
  jekyll-titles-from-headings

ADD --chown=jekyll:jekyll start.sh site-defaults.yml site-overrides.yml /site/

ENTRYPOINT ["/site/start.sh"]

CMD ["build"]