#
# Docker compose configuration file for NIST Pages PDF support.
#
# From https://github.com/bspk/nistpages-docker/blob/master/pdf/docker-compose-pdf.yml
#

version: '3'

services:
  server:
    image: jricher/nistpages-pdf
    volumes:
      - "${NISTPAGES_SOURCE}:/opt/source"
      - .:/opt/pdf
    command: /opt/pdf/pdf.sh
    working_dir: /opt/work
    
